### ISSUE TITLE
release 태그 사용 정하기

### ISSUE THREAD

**Issue by suhsein** [suhsein/2022_OSS_Teamproject#19]
* Commit 시 태그를 사용할 지 여부와 사용한다면 어떤 태그를 사용할 것인가?

**Comment by hyein0229** [comment]
Major.Minor.Patch 방법을 사용
Major: 기존 버전과 호환이 되지 않는 경우
Minor: 기존과 호환이 가능하면서 새로운 기능 추가의 경우
Patch:  기존과 호환이 가능하면서 버그 수정의 경우
